" .vimrc : Si Beaumont
" vim: foldmethod=marker

" General {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible

" Also add merlin to the run time path
let s:ocamlmerlin=substitute(system('opam config var share'),'\n$','','''') .  "/ocamlmerlin"
execute "set rtp+=".s:ocamlmerlin."/vim"
execute "set rtp+=".s:ocamlmerlin."/vimbufsync"

" Set to auto read when a file is changed from the outside
set autoread

" Search for tags file in pwd then search backwards until /
set tags=tags;/

" Change the mapleader from \ to ,
let mapleader=","
let maplocalleader=","

" Use extended unicode mouse escape sequences (wide terminal support)
if has('mouse_sgr')
    set ttym=sgr
endif

" Get rid of nasty lag on ESC (timeout and ttimeout seem useless)
au InsertEnter * set timeoutlen=1
au InsertLeave * set timeoutlen=1000
" }}}

" UI {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
syntax on

set guifont=Monospace\ 9

set mouse=a         " use the mouse in terminal mode

set go-=T           " no toolbar in gvim
set scrolloff=4     " lines of context when scrolling

set wildmode=longest,list     " bash-style file completion
set wildignore=*.o,*~,*.pyc   " Ignore compiled files

set ruler           " show current position
set colorcolumn=80  " always show width marker
set number          " always show line numbers
set cursorline      " highlight the current line

set showcmd         " display commands as entered
set cmdheight=2     " Height of the command bar
set laststatus=2    " Required for vim-powerline

set hidden          " allow hidden buffers

set showmatch       " show matching parenthesis
set matchtime=2     " show for 2 tenths of a second

set ignorecase      " ignore case when searching...
set smartcase       " ...unless I use case to search
set hlsearch        " highlight search terms
set incsearch       " show search matches as you type

set splitbelow      " open new splits below
set splitright      " open new vsplits to the right

set lazyredraw      " don't redraw during macros

set list                    " show invisibles
set listchars=tab:┼─,eol:¬  " another nice option is tab:▸\ 
set showbreak=↪\            " useful indication of wrapping

set foldmethod=marker   " fold on markers
set foldlevel=100       " ...but not by default

" use sensible regex
nnoremap / /\v
vnoremap / /\v

" sensible moving on wrapped lines
noremap j gj
noremap k gk
noremap 0 g0
noremap $ g$

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
" }}}

" Autocommands {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
au BufRead {*xensource.log*,*SMlog*,*messages*} setl ft=messages
au FileType ocaml                               setl noet fo-=t
" }}}

" Files, backups and undo {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if version >= 703
    set undodir=~/.vim/tmp/undo// " undo files
endif
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set backup                        " enable backups
set swapfile                      " noswapfile has bitten me!
" }}}

" Text editing {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set wrap
set textwidth=79
set formatoptions=qrn1t

set expandtab     " use tabs instead of spaces
set smarttab      " insert tabs at start of line with shiftwidth, not tabstop
set tabstop=4     " a tab is four spaces
set shiftwidth=4  " number of spaces to use for autoindenting

set backspace=indent,eol,start  " backpace over everything in insert mode

set autoindent    " always set autoindenting on
set smartindent   " for some auto-semantic-indenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'
" }}}

" Key mappings {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" (Slightly) quicker saving of files
nmap <leader>w :w!<CR>

" Sudo write (if we forgot to sudo vim)---super handy!
cnoreabbrev w!! w !sudo tee % >/dev/null

" Change to directory of file in current buffer
map <leader>cd :cd %:p:h<CR>:pwd<CR>

" Clear the highlight from the last search
nnoremap <silent> <leader>/ :nohlsearch<CR>

" Disable width-marker when needed
map <leader>m :set colorcolumn=<CR>

" Focus on current fold, close the rest
nnoremap <leader>z zMzvzz

" System clipboard interaction
noremap <leader>y "+y
noremap <leader>p :set paste<CR>"+p<CR>:set nopaste<CR>
noremap <leader>P :set paste<CR>"+P<CR>:set nopaste<CR>
vnoremap <leader>y "+ygv

" Clean trailing whitespace from whole file
nnoremap <leader>W mz:%s/\s\+$//<cr>:let @/=''<cr>`z

" Rerun ctags over directory
nmap <F8> :!/usr/bin/ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

" Quickly edit my todo file
nmap <silent> <leader>et :e /work/todo.txt<CR>:set ft=pandoc<CR>
nmap <silent> <leader>mi ^wy$/Worklog\n\=\=\=\=\=\=\=<CR>:nohlsearch<CR>j:read !date --rfc-3339='date'<CR>A: <ESC>p^
nmap <silent> <leader>md ,mi<C-o>dd

" Moving around splits with the leader key
nmap <silent> <leader>h :wincmd h<CR>
nmap <silent> <leader>j :wincmd j<CR>
nmap <silent> <leader>k :wincmd k<CR>
nmap <silent> <leader>l :wincmd l<CR>
" }}}

" Plugin configuration {{{
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
filetype off
runtime macros/matchit.vim
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'altercation/vim-colors-solarized'
let g:solarized_termtrans=1
let g:solarized_termcolors=16
let g:solarized_visibility='normal'
if &t_Co >= 16 || has("gui_running")
    colorscheme solarized
    set bg=dark
    highlight ExtraWhitespace ctermbg=DarkRed ctermfg=Red
endif


Bundle 'Raimondi/delimitMate'
Bundle 'scrooloose/syntastic'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-liquid'
Bundle 'tpope/vim-markdown'

Bundle 'mileszs/ack.vim'
nmap <leader>a :Ack 

Bundle 'majutsushi/tagbar'
let g:tagbar_ctags_bin='/usr/bin/ctags'
let g:tagbar_width=30
let g:tagbar_autofocus=1
nmap <silent> <leader>r :TagbarToggle<CR>

Bundle 'Lokaltog/vim-powerline'
let g:Powerline_symbols = 'fancy'
let g:Powerline_cache_enabled = 1
let Powerline_colorscheme="solarized16"

Bundle 'scrooloose/nerdtree'
let NERDTreeIgnore = [
    \ '\.pyc$',
    \ '\.cm\(x\(a\)\?\|i\|t\)$',
    \ '\.sp\(o\|i\)t$',
    \ '\.o\(\(pt\|mc\)\)\=$',
    \ '\.annot$']
nmap <silent> <leader>O :NERDTreeFind<CR>
nmap <silent> <leader>o :NERDTreeToggle<CR>

Bundle 'scrooloose/nerdcommenter'
let g:NERDSpaceDelims=1
let g:NERDRemoveExtraSpaces=1

Bundle 'klen/python-mode'
let g:pymode_run=0
let g:pymode_breakpoint=0
let g:pymode_utils_whitespaces=0
let g:pymode_lint_hold=0

Bundle 'YankRing.vim'
let g:yankring_history_file='.yankring-hist'

filetype plugin indent on
" }}}
