" .vimrc : Si Beaumont
" vim: foldmethod=marker

" General {{{1
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" This must be first, because it changes other options as side effect
set nocompatible

" Use pathogen to manage plugins under ~/.vim/bundle
call pathogen#infect()
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Set to auto read when a file is changed from the outside
set autoread

" Enable filetype plugins
filetype plugin indent on

" Change the mapleader from \ to ,
let mapleader=","

" Use extended unicode mouse escape sequences
if has('mouse_sgr')
    set ttym=sgr
endif

" Get rid of nasty lag on ESC (timeout and ttimeout seem useless)
au InsertEnter * set timeoutlen=1
au InsertLeave * set timeoutlen=1000

" UI {{{1
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set guifont=Monospace\ 9

set mouse=a         " use the mouse in terminal mode

set go-=T           " no toolbar in gvim
set scrolloff=4     " lines of context when scrolling

set wildmode=longest,list     " bash-style file completion
set wildignore=*.o,*~,*.pyc   " Ignore compiled files

set ruler           " Show current position
set colorcolumn=80  " always show width marker
set number          " always show line numbers
set cursorline      " highlight the current line

set cmdheight=2     " Height of the command bar

set hidden          " Handle hidden buffers

set showmatch       " show matching parenthesis
set matchtime=2     " show for 2 tenths of a second

set ignorecase      " ignore case when searching...
set smartcase       " ...unless I use case to search
set hlsearch        " highlight search terms
set incsearch       " show search matches as you type

set splitbelow      " open new splits below
set splitright      " open new vsplits to the right

" use sensible regex
nnoremap / /\v
vnoremap / /\v

set lazyredraw      " don't redraw during macros

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=

" Show invisibles (in Textmate style)
set list
set listchars=tab:▸\ ,eol:¬

" Folding
set foldmethod=marker
set foldcolumn=2

" Colours {{{1
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" I have 256 colors even if my TERM variable says otherwise (tmux)
set t_Co=256
" Let's try to always have colours
if &t_Co >= 256 || has("gui_running")
    colorscheme mustang
endif
if &t_Co > 2 || has("gui_running")
   " switch syntax highlighting on, when the terminal has colors
   syntax on
endif

" Custom ft recognition
au BufRead,BufNewFile *xensource.log* set filetype=messages
au BufRead,BufNewFile *isl_trace.log* set filetype=messages
au BufRead,BufNewFile *SMlog* set filetype=messages
au BufRead,BufNewFile *messages* set filetype=messages

" Higlight long lines
"highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"match OverLength /\%81v.\+/

" Files, backups and undo {{{1
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if version >= 703
    set undodir=~/.vim/tmp/undo// " undo files
endif
set backupdir=~/.vim/tmp/backup// " backups
set directory=~/.vim/tmp/swap//   " swap files
set backup                        " enable backups
set noswapfile                    " It's 2012, Vim.

" Text editing {{{1
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set wrap
set textwidth=79
set formatoptions=qrn1t
set showbreak=↪\  " useful indication of wrapping

set expandtab     " use tabs instead of spaces
set smarttab      " insert tabs at start of line with shiftwidth, not tabstop
set tabstop=4     " a tab is four spaces
set shiftwidth=4  " number of spaces to use for autoindenting

set backspace=indent,eol,start
                  " allow backspacing over everything in insert mode

set autoindent    " always set autoindenting on
set smartindent   " for some auto-semantic-indenting
set shiftround    " use multiple of shiftwidth when indenting with '<' and '>'

" Plugin configuration {{{1
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" ctags
set tags=tags;/
set complete+=t

" Tagbar
let g:tagbar_ctags_bin='/usr/bin/ctags'
let g:tagbar_width=30
let g:tagbar_autofocus=1

" Vim Powerline
let g:Powerline_symbols = 'fancy'
let g:Powerline_cache_enabled = 1
set laststatus=2                    " required for vim-powerline

" NERDTree
let NERDTreeIgnore = ['\.pyc$']

" NERDCommenter
let g:NERDSpaceDelims=1
let g:NERDRemoveExtraSpaces=1

" Python mode (disable stuff for working with shared (and bad) code
let g:pymode_run=0
let g:pymode_breakpoint=0
let g:pymode_utils_whitespaces=0
let g:pymode_lint_hold=0

" YankRing
let g:yankring_history_file='.yankring-hist'

" Pandoc
let g:pandoc_use_hard_wraps=1

" Functions {{{1
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" See what you've changed before saving
function! s:DiffWithSaved()
    let filetype=&ft
    diffthis
    vnew | r # | normal! 1Gdd
    diffthis
    exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
com! DiffSaved call s:DiffWithSaved()

" Key mappings {{{1
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Quickly edit/reload the vimrc file
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" (Slightly) quicker saving of files
nmap <leader>w :w!<CR>

" Sudo write (if we forgot to sudo vim)---super handy!
cnoreabbrev w!! w !sudo tee % >/dev/null

" Change to directory of file in current buffer
map <leader>cd :cd %:p:h<CR>:pwd<CR>

" Clear the highlight from the last search
nnoremap <silent> <leader>/ :nohlsearch<CR>

" Disable width-marker when needed
map <leader>m :set colorcolumn=<CR>

" Focus on current fold, close the rest
nnoremap <leader>z zMzvzz

" System clipboard interaction
noremap <leader>y "*y
noremap <leader>p :set paste<CR>"*p<CR>:set nopaste<CR>
noremap <leader>P :set paste<CR>"*P<CR>:set nopaste<CR>
vnoremap <leader>y "*ygv

" Clean trailing whitespace from whole file
nnoremap <leader>W mz:%s/\s\+$//<cr>:let @/=''<cr>`z

" Version control blame in Vim
vmap <Leader>g :<C-U>!git blame <C-R>=expand("%:p") <CR> \| sed -n <C-R>=line("'<") <CR>,<C-R>=line("'>") <CR>p <CR>
vmap <Leader>h :<C-U>!hg blame -ucdq <C-R>=expand("%:p") <CR> \| sed -n <C-R>=line("'<") <CR>,<C-R>=line("'>") <CR>p <CR>

" Rerun ctags over directory
nmap <F8> :!/usr/bin/ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

" Opening sidebars (NERDTree on left, Tagbar on right)
nmap <silent> <leader>r :TagbarToggle<CR>
nmap <silent> <leader>O :NERDTreeFind<CR>
nmap <silent> <leader>o :NERDTreeToggle<CR>

" Ack in pwd...
nmap <leader>a :Ack 

" Quickly edit my todo file
nmap <silent> <leader>et :e /work/todo.txt<CR>:set ft=pandoc<CR>
nmap <silent> <leader>mi ^y$/\=\=\=<CR>,/o<ESC>p^r-
nmap <silent> <leader>md ^cl☑<space><esc>

" Log to SMlog (work stuff)
nmap <silent> <leader>sm yEoutil.SMlog("sjbx: pa = %s" % p

" Moving around splits with the leader key
nmap <silent> <leader>h :wincmd h<CR>
nmap <silent> <leader>j :wincmd j<CR>
nmap <silent> <leader>k :wincmd k<CR>
nmap <silent> <leader>l :wincmd l<CR>
