# Note: .bash_profile is sourced for login shells (every shell under Mac OSX)

# This file is sourced by bash when you log in interactively.
[ -f ~/.bashrc ] && . ~/.bashrc

# MacPorts...
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
