# Give me 256 colors! gnome-terminal hardcodes TERM to xterm...
[ $TERM = xterm ] && export TERM=xterm-256color

# Linux tools and Mac homebrews
[ -r "/usr/local/bin" ] && export PATH="/usr/local/bin:$PATH"
# Tmux from homebrew (xcode updates clobber /usr/local/bin/tmux)
[ -r "/usr/local/opt/tmux/bin" ] && export PATH="/usr/local/opt/tmux/bin:$PATH"
# Cabal
[ -r "$HOME/.cabal/bin" ] && export PATH="$HOME/.cabal/bin:$PATH"
# Scripts
[ -r "$HOME/bin" ] && export PATH="$HOME/bin:$PATH"
# OPAM
which opam &>/dev/null && eval $(opam config env | grep -v MANPATH)
# Load RVM into a shell session *as a function*
[ -r "/local/rvm/scripts/rvm" ] && source "/local/rvm/scripts/rvm"
# Homebrew GNU coreutils
[ -r "/usr/local/opt/coreutils/libexec/gnubin" ] && export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
# iTerm shell integration
[ -r "$HOME/.iterm2_shell_integration.bash" ] && source "$HOME/.iterm2_shell_integration.bash"
# Python from Homebrew
[ -r "/usr/local/opt/python/libexec/bin" ] && export PATH="/usr/local/opt/python/libexec/bin:$PATH"
# Miniconda3
[ -r "$HOME/miniconda3/bin" ] && export PATH="$HOME/miniconda3/bin:$PATH"
# Python3.6 from miniconda
[ -r "$HOME/miniconda3/envs/py3.6/bin" ] && export PATH="$HOME/miniconda3/envs/py3.6/bin:$PATH"
# Python2.7 from miniconda
[ -r "$HOME/miniconda3/envs/py2.7/bin" ] && export PATH="$HOME/miniconda3/envs/py2.7/bin:$PATH"
# Ruby
which rbenv &>/dev/null && eval "$(rbenv init -)"

# $MANPATH updates -- currently disabled as it borks built in Mac MANPATH
# [ -r "/usr/local/opt/coreutils/libexec/gnuman" ] && export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
# which opam &>/dev/null && eval $(opam config env | grep MANPATH)

# Xmodmap
[[ $OSTYPE =~ ^linux ]] && xmodmap "$HOME/.Xmodmap"

# bash completion
[ -r "/usr/local/etc/bash_completion" ] && source "/usr/local/etc/bash_completion"
[ -r "/usr/share/bash-completion/bash_completion" ] && source "/usr/share/bash-completion/bash_completion"

# dircolors
which dircolors &>/dev/null && eval $(dircolors ~/.dircolors)

# editor
export EDITOR="vim"
export GIT_EDITOR="vim"

# history
export HISTCONTROL="ignoreboth"
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:reboot"

# display
[ -z "$DISPLAY" ] && DISPLAY=":0.0"

# shell options
shopt -s checkwinsize
stty -ixon

# additional files to source
for file in ~/.{bash_prompt,aliases,functions,tokens,localrc}; do
    [ -r "$file" ] && source "$file"
done
unset file
